<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Martlet.Avatars\Martlet.Avatars.csproj" />
    <Using Include="Xunit" />
    <None Include="..\..\contracts\avatars\frame-v1.json" Link="frame-v1.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\contracts\avatars\frame-v1.schema.json" Link="frame-v1.schema.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\contracts\avatars\configuration-v1.json" Link="configuration-v1.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
