<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Martlet.Core\Martlet.Core.csproj" />
    <InternalsVisibleTo Include="Martlet.Launcher" />
    <InternalsVisibleTo Include="Martlet.Updates.Tests" />
    <InternalsVisibleTo Include="Martlet.Launcher.Tests" />
  </ItemGroup>
</Project>
