using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using Martlet.Avatar.Audio2Face.Remote;
using Martlet.Avatar.Hosting;
using Martlet.Avatars;
using Martlet.Core.Characters;
using Martlet.Core.Contracts;
using Martlet.Gateway;

namespace Martlet.NodeLinkCheck;

/// <summary>
/// Rehearses the shared character models end to end on this PC with the production code: two real gateways (Kestrel, pinned
/// TLS) on 127.0.0.1 with an in-memory copy of character-models.json and the pieces, and three simulated desktops that keep
/// their character copies in a temporary folder and use the desktop's paired client and Martlet.Avatar.Hosting's import and
/// reconcile engine, reading models with the character renderer's own file reader. The fixture models are generated bytes
/// in the Live2D folder and VRM file shapes (NOT real models; nothing is rendered). Nothing leaves loopback; the temporary
/// folder is deleted afterwards and nothing touches the credential vault.
/// </summary>
internal static class CharacterRehearsal
{
    internal static async Task<(bool Ok, object Report)> RunAsync(CancellationToken token)
    {
        var steps = new List<(string Name, bool Ok, string Detail)>();
        var started = DateTimeOffset.UtcNow;
        var root = Path.Combine(Path.GetTempPath(), "martlet-character-rehearsal-" + Guid.NewGuid().ToString("N"));
        await using var h1 = await ModelHost.StartAsync("lab-host-1");
        await using var h2 = await ModelHost.StartAsync("lab-host-2");
        var a = new LabDesktop("lab-desktop-a", Path.Combine(root, "a"));
        var b = new LabDesktop("lab-desktop-b", Path.Combine(root, "b"));
        var c = new LabDesktop("lab-desktop-c", Path.Combine(root, "c"));
        var (live2dPath, vrmPath) = WriteFixtures(Path.Combine(root, "originals"));
        CharacterModel? live2d = null, vrm = null;
        CharacterModelLibrary? beforeRemoval = null;

        async Task Run(string name, Func<Task<(bool Ok, string Detail)>> action)
        {
            try
            {
                var (ok, detail) = await action();
                steps.Add((name, ok, detail));
            }
            catch (Exception error) when (error is not OperationCanceledException || !token.IsCancellationRequested)
            {
                steps.Add((name, false, $"{error.GetType().Name}: {error.Message}"));
            }
        }

        try
        {
            await Run("Desktops A, B and C pair with lab-host-1 and lab-host-2 (signed, pinned connections)", async () =>
            {
                foreach (var desktop in new[] { a, b, c })
                foreach (var host in new[] { h1, h2 })
                    await desktop.PairAsync(host);
                return (true, "each desktop paired with both hosts");
            });
            await Run("A adds a Live2D model folder and a VRM file: Martlet keeps its own copy, read exactly like the originals", async () =>
            {
                live2d = await SharedCharacterModels.ImportAsync(a.DataDirectory, AvatarRenderer.Live2D, live2dPath, "Fixture Live2D", a.DeviceId,
                    DateTimeOffset.UtcNow, token);
                vrm = await SharedCharacterModels.ImportAsync(a.DataDirectory, AvatarRenderer.Vrm, vrmPath, "Fixture VRM", a.DeviceId,
                    DateTimeOffset.UtcNow.AddSeconds(1), token);
                var library = SharedCharacterModels.View(a.DataDirectory);
                var same = await SameAsync(AvatarRenderer.Live2D, live2dPath, SharedCharacterModels.EntryPath(a.DataDirectory, live2d), token) &&
                    await SameAsync(AvatarRenderer.Vrm, vrmPath, SharedCharacterModels.EntryPath(a.DataDirectory, vrm), token);
                return (library.Live.Count == 2 && same && SharedCharacterModels.IsComplete(a.DataDirectory, live2d) &&
                        SharedCharacterModels.IsComplete(a.DataDirectory, vrm) && live2d.Files!.Count == 4 &&
                        live2d.Files.Sum(f => f.Chunks.Count) == 6 && vrm.Files!.Single().Chunks.Count == 2,
                    $"list: {library.Live.Count} characters; Live2D: {live2d.Files!.Count} files, {live2d.Files.Sum(f => f.Chunks.Count)} pieces, " +
                    $"{live2d.Bytes:N0} bytes; VRM: {vrm.Files!.Single().Chunks.Count} pieces, {vrm.Bytes:N0} bytes; copies read like the originals: {same}");
            });
            await Run("A shares the list and every piece with lab-host-1 (each piece is one signed request under the gateway's limit)", async () =>
            {
                var present = await a.ShareAsync(h1, token);
                var expected = SharedCharacterModels.View(a.DataDirectory).LiveChunks();
                return (present.SetEquals(expected.Keys) && h1.SavedChunks.Count == expected.Count && h1.SavedLibrary is not null &&
                        expected.Values.Max() == CharacterModelLibrary.ChunkBytes,
                    $"lab-host-1 holds {present.Count} of {expected.Count} pieces (largest {expected.Values.Max():N0} bytes); saved: character-models.json and {h1.SavedChunks.Count} pieces");
            });
            await Run("Desktop B, new and empty, takes both characters from lab-host-1; its copies match the originals byte for byte", async () =>
            {
                var fetched = 0;
                var result = await b.SyncAsync(h1, (sha256, t) => { fetched++; return b.FetchAsync(h1, sha256, t); }, token);
                var same = await SameAsync(AvatarRenderer.Live2D, live2dPath, SharedCharacterModels.EntryPath(b.DataDirectory, live2d!), token) &&
                    await SameAsync(AvatarRenderer.Vrm, vrmPath, SharedCharacterModels.EntryPath(b.DataDirectory, vrm!), token);
                return (result.Added == 2 && result.Waiting == 0 && result.Local.Count == 2 && same && fetched == 8,
                    $"B copied {result.Added} characters ({fetched} pieces); waiting: {result.Waiting}; identical to the originals: {same}");
            });
            await Run("An interrupted copy continues where it stopped: desktop C loses lab-host-1 after 3 pieces, then fetches only the rest", async () =>
            {
                var first = 0;
                var one = await c.SyncAsync(h1, async (sha256, t) => ++first > 3 ? null : await c.FetchAsync(h1, sha256, t), token);
                var second = 0;
                var two = await c.SyncAsync(h1, (sha256, t) => { second++; return c.FetchAsync(h1, sha256, t); }, token);
                return (one.Added == 0 && one.Waiting == 2 && two.Added == 2 && two.Waiting == 0 && second == 8 - 3,
                    $"first pass: {one.Added} complete, {one.Waiting} waiting; second pass fetched {second} pieces and completed {two.Added}");
            });
            await Run("B passes the characters on to lab-host-2, which A never reached", async () =>
            {
                var present = await b.ShareAsync(h2, token);
                var expected = SharedCharacterModels.View(b.DataDirectory).LiveChunks();
                return (present.SetEquals(expected.Keys) && h2.SavedChunks.Count == expected.Count,
                    $"lab-host-2 holds {present.Count} of {expected.Count} pieces, all sent by B");
            });
            await Run("B removes the VRM: both hosts delete its pieces and A deletes its copy", async () =>
            {
                beforeRemoval = SharedCharacterModels.View(a.DataDirectory);
                await SharedCharacterModels.RemoveAsync(b.DataDirectory, vrm!.Id, b.DeviceId, DateTimeOffset.UtcNow, null, token);
                var on1 = await b.MergeAsync(h1, token);
                var on2 = await b.MergeAsync(h2, token);
                var result = await a.SyncAsync(h1, (sha256, t) => a.FetchAsync(h1, sha256, t), token);
                var vrmChunks = vrm.Files!.Single().Chunks;
                return (!vrmChunks.Any(on1.Present.Contains) && !vrmChunks.Any(on2.Present.Contains) && !vrmChunks.Any(h1.SavedChunks.ContainsKey) &&
                        result.Removed == 1 && !Directory.Exists(SharedCharacterModels.Folder(a.DataDirectory, vrm.Id)) &&
                        !Directory.Exists(SharedCharacterModels.Folder(b.DataDirectory, vrm.Id)),
                    $"lab-host-1 holds {on1.Present.Count} pieces, lab-host-2 {on2.Present.Count}; A deleted {result.Removed} copy; B's copy deleted: {!Directory.Exists(SharedCharacterModels.Folder(b.DataDirectory, vrm.Id))}");
            });
            await Run("An older copy (from before the removal) can't bring the VRM back", async () =>
            {
                var merged = await a.MergeAsync(h1, token, beforeRemoval!);
                return (merged.Library.Find(vrm!.Id)?.Removed == true && !vrm.Files!.Single().Chunks.Any(merged.Present.Contains),
                    $"after merging the stale copy the VRM is {(merged.Library.Find(vrm.Id)?.Removed == true ? "still removed" : "back")}");
            });
            await Run("C shows the Live2D character; A removes it: C keeps its copy while it shows it, and the list no longer has it", async () =>
            {
                await SharedCharacterModels.RemoveAsync(a.DataDirectory, live2d!.Id, a.DeviceId, DateTimeOffset.UtcNow, null, token);
                await a.MergeAsync(h1, token);
                var shown = new HashSet<string>([SharedCharacterModels.Key(live2d.Id)], StringComparer.OrdinalIgnoreCase);
                var kept = await c.SyncAsync(h1, (sha256, t) => c.FetchAsync(h1, sha256, t), token, shown);
                var keptCopy = SharedCharacterModels.KeyOfPath(c.DataDirectory, SharedCharacterModels.EntryPath(c.DataDirectory, live2d)) is not null &&
                    await SameAsync(AvatarRenderer.Live2D, live2dPath, SharedCharacterModels.EntryPath(c.DataDirectory, live2d), token);
                var later = await c.SyncAsync(h1, (sha256, t) => c.FetchAsync(h1, sha256, t), token);
                return (kept.Library.Live.Count == 0 && keptCopy && later.Removed == 1 && !Directory.Exists(SharedCharacterModels.Folder(c.DataDirectory, live2d.Id)),
                    $"while shown: copy kept and readable: {keptCopy}; after choosing another character: {later.Removed} copy deleted");
            });
            await Run("lab-host-1 restarts from its saved copy and still serves every piece of a newly added character", async () =>
            {
                var again = await SharedCharacterModels.ImportAsync(a.DataDirectory, AvatarRenderer.Vrm, vrmPath, "Fixture VRM again", a.DeviceId,
                    DateTimeOffset.UtcNow, token);
                await a.ShareAsync(h1, token);
                var before = (await a.ReadAsync(h1, token)).Present.Count;
                await h1.RestartAsync();
                var after = await a.ReadAsync(h1, token);
                var chunk = await a.FetchAsync(h1, again.Files!.Single().Chunks[0], token);
                return (after.Present.Count == before && before == 2 && after.Library.Find(again.Id) is { Removed: false } && chunk is not null,
                    $"pieces before {before}, after restart {after.Present.Count}; first piece readable: {chunk is not null}");
            });
            await Run("Pieces are checked: a wrong SHA-256, a piece no character has and a piece of a removed character are refused", async () =>
            {
                var model = SharedCharacterModels.View(a.DataDirectory).Live.Single();
                var other = RandomNumberGenerator.GetBytes(1_000);
                var wrong = await Code(() => a.SendAsync(h1, model.Files!.Single().Chunks[1], other, token));
                var unknown = await Code(() => a.SendAsync(h1, Convert.ToHexStringLower(SHA256.HashData(other)), other, token));
                var removedPiece = await File.ReadAllBytesAsync(live2dPath, token);
                var removed = await Code(() => a.SendAsync(h1, CharacterModelLibrary.File("x", removedPiece).Chunks[0], removedPiece, token));
                return (wrong == "request.invalid" && unknown == "request.invalid" && removed == "request.invalid" &&
                        live2d!.Files!.Any(f => f.Chunks.Contains(CharacterModelLibrary.File("x", removedPiece).Chunks[0])),
                    $"wrong SHA-256: {wrong}; not in the list: {unknown}; a removed character's piece: {removed}");
            });
            await Run("Reading a piece the host doesn't hold answers chunk.missing (none)", async () =>
            {
                var missing = await a.FetchAsync(h1, new string('0', 64), token);
                return (missing is null, missing is null ? "no piece" : "unexpected bytes");
            });
            await Run("The list keeps its limits: a 17th character is refused, and so is a Live2D model that refers to a script", async () =>
            {
                var library = CharacterModelLibrary.Empty;
                for (var i = 0; i < CharacterModelLibrary.MaximumModels; i++)
                    library = library.Add($"Tiny {i}", CharacterModelLibrary.Vrm, $"tiny{i}.vrm",
                        [CharacterModelLibrary.File($"tiny{i}.vrm", Encoding.ASCII.GetBytes("glTF" + i))], a.DeviceId, DateTimeOffset.UtcNow.AddSeconds(i));
                var full = Refused(() => library.Add("One more", CharacterModelLibrary.Vrm, "more.vrm",
                    [CharacterModelLibrary.File("more.vrm", Encoding.ASCII.GetBytes("glTF-more"))], a.DeviceId, DateTimeOffset.UtcNow));
                var folder = Path.Combine(root, "scripted");
                Directory.CreateDirectory(folder);
                await File.WriteAllTextAsync(Path.Combine(folder, "m.model3.json"),
                    "{\"Version\":3,\"FileReferences\":{\"Moc\":\"m.moc3\",\"Textures\":[],\"UserData\":\"run.js\"}}", token);
                await File.WriteAllBytesAsync(Path.Combine(folder, "m.moc3"), [1], token);
                await File.WriteAllTextAsync(Path.Combine(folder, "run.js"), "alert(1)", token);
                var scripted = await RefusedAsync(() => SharedCharacterModels.ImportAsync(a.DataDirectory, AvatarRenderer.Live2D,
                    Path.Combine(folder, "m.model3.json"), "Scripted", a.DeviceId, DateTimeOffset.UtcNow, token));
                return (full && scripted && SharedCharacterModels.View(a.DataDirectory).Live.Count == 1,
                    $"17th character refused: {full}; model that refers to a script refused: {scripted}");
            });
        }
        finally
        {
            try { if (Directory.Exists(root)) Directory.Delete(root, recursive: true); }
            catch (Exception error) when (error is IOException or UnauthorizedAccessException) { }
        }

        var ok = steps.All(s => s.Ok);
        return (ok, new
        {
            ok,
            passed = steps.Count(s => s.Ok),
            total = steps.Count,
            seconds = Math.Round((DateTimeOffset.UtcNow - started).TotalSeconds, 1),
            scope = "Two real gateways on 127.0.0.1 (Kestrel, pinned TLS) with in-memory character-models.json and pieces, and three " +
                "simulated desktops using the desktop's paired client and Martlet.Avatar.Hosting's import and reconcile engine over " +
                "a temporary folder, with generated fixture files in the Live2D folder and VRM file shapes (NOT real models, nothing " +
                "rendered). Not covered: the desktop window and its 30-second sync, the Linux host's files, rendering a copied model " +
                "and a real LAN.",
            steps = steps.Select(s => new { step = s.Name, ok = s.Ok, detail = s.Detail })
        });
    }

    // A Live2D-shaped folder (model3.json, a 7 MiB .moc3 that travels in three pieces, a texture and a motion in subfolders)
    // and a 4 MiB VRM-shaped file (two pieces). Generated bytes, NOT real models.
    private static (string Live2D, string Vrm) WriteFixtures(string directory)
    {
        var live2d = Path.Combine(directory, "Fixture");
        Directory.CreateDirectory(Path.Combine(live2d, "textures"));
        Directory.CreateDirectory(Path.Combine(live2d, "motions"));
        var model = Path.Combine(live2d, "Fixture.model3.json");
        File.WriteAllText(model, "{\"Version\":3,\"FileReferences\":{\"Moc\":\"Fixture.moc3\",\"Textures\":[\"textures/texture_00.png\"]," +
            "\"Motions\":{\"Idle\":[{\"File\":\"motions/idle.motion3.json\"}]}}}");
        // Files a model doesn't declare (VTube Studio settings, readmes) stay behind and are never copied.
        File.WriteAllText(Path.Combine(live2d, "readme.txt"), "not part of the model");
        File.WriteAllBytes(Path.Combine(live2d, "Fixture.moc3"), Bytes(7 * 1024 * 1024 + 123, 1));
        File.WriteAllBytes(Path.Combine(live2d, "textures", "texture_00.png"), Bytes(200_000, 2));
        File.WriteAllText(Path.Combine(live2d, "motions", "idle.motion3.json"), "{\"Version\":3}");
        var vrm = Path.Combine(directory, "Fixture.vrm");
        File.WriteAllBytes(vrm, Bytes(4 * 1024 * 1024, 3));
        return (model, vrm);

        static byte[] Bytes(int length, int seed)
        {
            var bytes = new byte[length];
            new Random(seed).NextBytes(bytes);
            return bytes;
        }
    }

    private static async Task<bool> SameAsync(AvatarRenderer renderer, string original, string copy, CancellationToken token)
    {
        var left = await LocalAvatarFiles.ReadModelAsync(renderer, original, token);
        var right = await LocalAvatarFiles.ReadModelAsync(renderer, copy, token);
        return left.Count == right.Count && left.OrderBy(x => x.Name, StringComparer.Ordinal).Zip(right.OrderBy(x => x.Name, StringComparer.Ordinal))
            .All(pair => pair.First.Name == pair.Second.Name && pair.First.Bytes.AsSpan().SequenceEqual(pair.Second.Bytes));
    }

    private static async Task<string?> Code(Func<Task> call)
    {
        try
        {
            await call();
            return null;
        }
        catch (Audio2FaceHostException error) { return error.Code; }
    }

    private static bool Refused(Action call)
    {
        try { call(); return false; }
        catch (ContractException) { return true; }
    }

    private static async Task<bool> RefusedAsync(Func<Task> call)
    {
        try { await call(); return false; }
        catch (ContractException) { return true; }
    }

    /// <summary>A simulated desktop: its pairings (secrets in memory) and its data folder, with the calls the real desktop's
    /// sync makes.</summary>
    private sealed class LabDesktop(string deviceId, string dataDirectory)
    {
        private readonly Dictionary<string, (Audio2FaceHostPairing Pairing, string Secret)> pairings = new(StringComparer.Ordinal);
        internal string DeviceId => deviceId;
        internal string DataDirectory => dataDirectory;

        internal async Task PairAsync(ModelHost host)
        {
            var card = host.Server.Pairing.OpenWindow(new() { DeviceId = deviceId, DisplayName = deviceId.ToUpperInvariant(), Roles = [GatewayRole.Voice] });
            pairings[host.HostId] = await Audio2FaceHostClient.PairAsync(host.Origin, host.HostId, host.Identity.SpkiFingerprint, deviceId,
                card.PairingId, card.Token.Reveal());
        }

        internal async Task<HostCharacterModels> ReadAsync(ModelHost host, CancellationToken token)
        {
            using var connection = Connect(host);
            return await connection.ReadCharacterModelsAsync(token);
        }

        internal async Task<HostCharacterModels> MergeAsync(ModelHost host, CancellationToken token, CharacterModelLibrary? library = null)
        {
            using var connection = Connect(host);
            var merged = await connection.MergeCharacterModelsAsync(library ?? SharedCharacterModels.View(dataDirectory), token);
            if (library is null) SharedCharacterModels.Commit(dataDirectory, merged.Library);
            return merged;
        }

        internal async Task<byte[]?> FetchAsync(ModelHost host, string sha256, CancellationToken token)
        {
            using var connection = Connect(host);
            return await connection.ReadCharacterModelChunkAsync(sha256, token);
        }

        internal async Task SendAsync(ModelHost host, string sha256, byte[] data, CancellationToken token)
        {
            using var connection = Connect(host);
            await connection.SendCharacterModelChunkAsync(sha256, data, token);
        }

        /// <summary>What the real sync does with one host's copy: merge it here, then copy what this desktop lacks.</summary>
        internal async Task<SharedCharacterModelsResult> SyncAsync(ModelHost host, Func<string, CancellationToken, Task<byte[]?>> fetch,
            CancellationToken token, IReadOnlySet<string>? keep = null)
        {
            SharedCharacterModels.Commit(dataDirectory, (await ReadAsync(host, token)).Library);
            return await SharedCharacterModels.ReconcileAsync(dataDirectory, fetch, keep, token);
        }

        /// <summary>What the real sync does for one host: merge the list, then send every piece it lacks.</summary>
        internal async Task<IReadOnlySet<string>> ShareAsync(ModelHost host, CancellationToken token)
        {
            var merged = await MergeAsync(host, token);
            var present = new HashSet<string>(merged.Present, StringComparer.Ordinal);
            var library = SharedCharacterModels.View(dataDirectory);
            using var connection = Connect(host);
            foreach (var model in library.Live.Where(m => SharedCharacterModels.IsComplete(dataDirectory, m)))
            foreach (var sha256 in model.Files!.SelectMany(f => f.Chunks).Distinct(StringComparer.Ordinal).Where(s => !present.Contains(s)).ToArray())
            {
                if (await SharedCharacterModels.ReadChunkAsync(dataDirectory, model, sha256, token) is not { } data) continue;
                present = [.. await connection.SendCharacterModelChunkAsync(sha256, data, token)];
            }
            return present;
        }

        // A restarted lab host has a new port and forgets volatile pairings; the desktop pairs again, as it would after a reset.
        private Audio2FaceHostConnection Connect(ModelHost host)
        {
            var (pairing, secret) = pairings[host.HostId];
            if (pairing.Origin != host.Origin)
            {
                PairAsync(host).GetAwaiter().GetResult();
                (pairing, secret) = pairings[host.HostId];
            }
            return new Audio2FaceHostConnection(pairing, secret);
        }
    }

    /// <summary>A real gateway on 127.0.0.1 with an in-memory copy of character-models.json and the pieces that survives a
    /// restart.</summary>
    private sealed class ModelHost : IAsyncDisposable, IGatewayCharacterModelStorage, IGatewayAuditSink
    {
        private X509Certificate2 certificate = null!;
        private GatewayListenerHandle? listener;
        internal GatewayServer Server { get; private set; } = null!;
        internal GatewayHostIdentity Identity { get; private set; } = null!;
        internal string HostId { get; private init; } = "";
        internal string Origin { get; private set; } = "";
        internal byte[]? SavedLibrary { get; private set; }
        internal Dictionary<string, byte[]> SavedChunks { get; } = new(StringComparer.Ordinal);

        internal static async Task<ModelHost> StartAsync(string hostId)
        {
            var host = new ModelHost { HostId = hostId, certificate = Certificate() };
            host.Identity = GatewayHostIdentity.FromCertificate(hostId, host.certificate);
            try
            {
                await host.ListenAsync();
                return host;
            }
            catch
            {
                await host.DisposeAsync();
                throw;
            }
        }

        private async Task ListenAsync()
        {
            Origin = $"https://127.0.0.1:{FreePort()}";
            var origin = new GatewayOrigin(Origin);
            Server = new GatewayServer(Identity, origin, [], this);
            Server.AttachCharacterModelStorage(this);
            listener = await Server.StartAsync(new GatewayTlsBinding(origin, Identity, certificate), new KestrelGatewayListenerFactory());
        }

        internal async Task RestartAsync()
        {
            if (listener is not null) await listener.DisposeAsync();
            listener = null;
            await ListenAsync();
        }

        public byte[]? LoadLibrary() => SavedLibrary;
        public void SaveLibrary(byte[] bytes) => SavedLibrary = bytes;
        public bool HasChunk(string sha256) => SavedChunks.ContainsKey(sha256);
        public byte[]? LoadChunk(string sha256) => SavedChunks.TryGetValue(sha256, out var bytes) ? (byte[])bytes.Clone() : null;
        public void SaveChunk(string sha256, byte[] bytes) => SavedChunks[sha256] = (byte[])bytes.Clone();
        public void RemoveChunk(string sha256) => SavedChunks.Remove(sha256);
        public void Record(GatewayAuditEvent gatewayEvent) { }

        public async ValueTask DisposeAsync()
        {
            if (listener is not null) await listener.DisposeAsync();
            listener = null;
            certificate?.Dispose();
        }

        private static int FreePort()
        {
            var probe = new TcpListener(IPAddress.Loopback, 0);
            probe.Start();
            try { return ((IPEndPoint)probe.LocalEndpoint).Port; }
            finally { probe.Stop(); }
        }

        private static X509Certificate2 Certificate()
        {
            using var key = ECDsa.Create(ECCurve.NamedCurves.nistP256);
            var request = new CertificateRequest("CN=Martlet character rehearsal (fixture)", key, HashAlgorithmName.SHA256);
            request.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, true));
            request.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature, true));
            request.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension(new OidCollection { new("1.3.6.1.5.5.7.3.1") }, true));
            var names = new SubjectAlternativeNameBuilder();
            names.AddIpAddress(IPAddress.Loopback);
            request.CertificateExtensions.Add(names.Build());
            var now = DateTimeOffset.UtcNow;
            using var ephemeral = request.CreateSelfSigned(now.AddDays(-1), now.AddDays(1));
            var password = Convert.ToHexString(RandomNumberGenerator.GetBytes(16));
            var pfx = ephemeral.Export(X509ContentType.Pkcs12, password);
            try { return X509CertificateLoader.LoadPkcs12(pfx, password, X509KeyStorageFlags.UserKeySet); }
            finally { CryptographicOperations.ZeroMemory(pfx); }
        }
    }
}
