<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Martlet.Gateway.Persistence.Portable.Tests\FakeLinuxFileSystem.cs" Link="FakeLinuxFileSystem.cs" />
    <Compile Include="..\Martlet.Gateway.Persistence.Portable.Tests\OwnerScenario.cs" Link="OwnerScenario.cs" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Martlet.Gateway.Host.Linux\Martlet.Gateway.Host.Linux.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
