<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <InternalsVisibleTo Include="Martlet.Gateway.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Persistence" />
    <InternalsVisibleTo Include="Martlet.Gateway.Persistence.Tests" />
  </ItemGroup>
</Project>
