<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Martlet.Diagnostics\Martlet.Diagnostics.csproj" />
    <ProjectReference Include="..\Martlet.Audio\Martlet.Audio.csproj" />
  </ItemGroup>
</Project>
