<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Martlet.Host.Setup\Martlet.Host.Setup.csproj" />
    <ProjectReference Include="..\..\src\Martlet.Host.Inventory\Martlet.Host.Inventory.csproj" />
    <ProjectReference Include="..\..\src\Martlet.HostArtifacts\Martlet.HostArtifacts.csproj" />
    <Using Include="Xunit" />
    <None Include="..\..\deploy\ubuntu\artifacts\host-artifacts.v1.json"
          Link="host-artifacts.v1.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\deploy\ubuntu\artifacts\host-artifacts.v2.json"
          Link="host-artifacts.v2.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Martlet.Host.Inventory.Tests\fixtures\*.v1.json"
          Link="fixtures\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
