namespace Martlet.Host.Setup;

public enum ArtifactAcquisitionFailure
{
    InvalidPlan,
    SetupPlanBlocked,
    SetupPlanChanged,
    SetupJournalMissing,
    SetupJournalChanged,
    ArtifactNotSelected,
    ContentPinMissing,
    DirectSourceUnavailable,
    ProviderUnsupported,
    RightsNotApproved,
    ConsentRequired,
    ConsentScopeMismatch,
    ConsentConsumed,
    PlanStale,
    PlanChanged,
    DestinationInvalid,
    FreeSpaceInsufficient,
    NetworkRefused,
    RedirectRejected,
    TransportFailed,
    ResponseInvalid,
    RangeUnsupported,
    ResumeStateMismatch,
    SourceChanged,
    ContentLengthMismatch,
    SizeExceeded,
    IntegrityMismatch,
    PartialConflict,
    FinalConflict,
    JournalCorrupt,
    JournalTooLarge,
    JournalChanged,
    JournalIoFailure,
    DiskFull,
    AccessDenied,
    StorageFailed,
    Timeout,
    Canceled,
    ProgressFailed,
    RegistryAuthenticationRejected,
    ImageMetadataInvalid,
    ImageInventoryMismatch,
    ImagePlatformMismatch,
    ImageBudgetExceeded,
    ImageRecoveryRequired,
    ImagePublicationUncertain,
    ImageLeaseUnavailable
}

public sealed record ArtifactAcquisitionRemedy(string Code, string Summary, string Instruction);

public static class ArtifactAcquisitionRemedies
{
    public static ArtifactAcquisitionRemedy For(ArtifactAcquisitionFailure failure) => failure switch
    {
        ArtifactAcquisitionFailure.InvalidPlan => new("ACQUIRE_PLAN_INVALID",
            "The artifact acquisition request is invalid or outside H05b bounds.",
            "Build a new preview from the exact H02 manifest, H05 setup plan, current setup journal, rights evidence, and owned artifact directory."),
        ArtifactAcquisitionFailure.SetupPlanBlocked => new("ACQUIRE_SETUP_BLOCKED",
            "The exact bound local review has not been durably recorded.",
            "Record a fresh LocalReview through the public review boundary. Host/runtime qualification remains separate from acquisition."),
        ArtifactAcquisitionFailure.SetupPlanChanged => new("ACQUIRE_SETUP_PLAN_CHANGED",
            "The owning setup plan or desired state changed.",
            "Preserve both journals, re-run read-only planning, and review the exact new setup and acquisition plans."),
        ArtifactAcquisitionFailure.SetupJournalMissing => new("ACQUIRE_SETUP_JOURNAL_MISSING",
            "No durable setup journal exists for the reviewed plan.",
            "Record the separately approved local review first. Review approval itself is never download consent."),
        ArtifactAcquisitionFailure.SetupJournalChanged => new("ACQUIRE_SETUP_JOURNAL_CHANGED",
            "The setup journal changed after the acquisition preview.",
            "Reconcile the current setup journal and create a fresh acquisition preview. Do not reuse consent from an earlier revision."),
        ArtifactAcquisitionFailure.ArtifactNotSelected => new("ACQUIRE_ARTIFACT_NOT_SELECTED",
            "The artifact is not in a role selected by the owning setup plan.",
            "Select the exact reviewed role and manifest artifact in a new setup plan; H05b never accepts an arbitrary URL or file."),
        ArtifactAcquisitionFailure.ContentPinMissing => new("ACQUIRE_CONTENT_PIN_MISSING",
            "The selected artifact lacks an exact payload SHA-256.",
            "Complete H02 content-pin evidence before acquisition. A Git object ID or URL is not a payload hash."),
        ArtifactAcquisitionFailure.DirectSourceUnavailable => new("ACQUIRE_DIRECT_SOURCE_REQUIRED",
            "The exact source identity lacks a supported pinned acquisition recipe.",
            "Review the canonical content/source pins. No arbitrary URL, mirror or redirect fallback is accepted."),
        ArtifactAcquisitionFailure.ProviderUnsupported => new("ACQUIRE_PROVIDER_UNSUPPORTED",
            "Acquisition for this provider or artifact kind is not supported.",
            "Use the separately reviewed named public provider recipe. Unsupported registries, platforms and Hugging Face remain metadata-only; do not substitute another URL or credential workflow."),
        ArtifactAcquisitionFailure.RightsNotApproved => new("ACQUIRE_RIGHTS_REQUIRED",
            "Exact license and intended-use evidence was not explicitly approved.",
            "Review every bound license claim and provide a separate exact rights-evidence fingerprint and revision. Approval defaults to No."),
        ArtifactAcquisitionFailure.ConsentRequired => new("ACQUIRE_CONSENT_REQUIRED",
            "Artifact download approval defaults to No.",
            "Review the exact source, bytes, hash, destination, free-space forecast, validators, setup journal, and rights evidence, then explicitly approve one attempt."),
        ArtifactAcquisitionFailure.ConsentScopeMismatch => new("ACQUIRE_CONSENT_SCOPE",
            "The approved scopes do not exactly match the acquisition preview.",
            "Approve exactly LocalJournal, ArtifactDownload, and ModelAndVoiceRights for this preview; blanket or partial consent is refused."),
        ArtifactAcquisitionFailure.ConsentConsumed => new("ACQUIRE_CONSENT_CONSUMED",
            "This one-use acquisition approval was already consumed.",
            "Create a fresh preview from current setup, source-validator, partial-file, disk, and journal facts before another request."),
        ArtifactAcquisitionFailure.PlanStale => new("ACQUIRE_PLAN_STALE",
            "The acquisition preview expired or was created in the future.",
            "Re-read current setup, disk, partial, and journal facts and explicitly review a new plan."),
        ArtifactAcquisitionFailure.PlanChanged => new("ACQUIRE_PLAN_CHANGED",
            "The acquisition plan no longer matches the approval or durable evidence.",
            "Preserve owned files, preview current facts, and approve the exact new fingerprint."),
        ArtifactAcquisitionFailure.DestinationInvalid => new("ACQUIRE_DESTINATION_INVALID",
            "The destination is not an exact owned file in the approved local staging directory.",
            "Choose an existing private non-link local staging directory. Acquisition does not install into the proposed deployment path."),
        ArtifactAcquisitionFailure.FreeSpaceInsufficient => new("ACQUIRE_DISK_INSUFFICIENT",
            "Observed destination-filesystem space is below the remaining payload plus reserve.",
            "Free or select reviewed space, then re-probe and approve a new plan. H05b deletes no unrelated file."),
        ArtifactAcquisitionFailure.NetworkRefused => new("ACQUIRE_NETWORK_REFUSED",
            "No verified artifact transport was explicitly composed.",
            "Use the typed production coordinator with fresh acquisition approval. Construction and preview remain offline."),
        ArtifactAcquisitionFailure.RedirectRejected => new("ACQUIRE_REDIRECT_REJECTED",
            "The source response violates the bounded provider redirect policy.",
            "Use the exact approved GitHub asset or named image registry recipe and its documented CDN hop; no arbitrary redirect or credentials are accepted."),
        ArtifactAcquisitionFailure.TransportFailed => new("ACQUIRE_TRANSPORT_FAILED",
            "The single approved HTTPS request failed.",
            "Check the exact public source and local network, then create a fresh preview. There is no automatic retry, mirror, credential, or protocol fallback."),
        ArtifactAcquisitionFailure.ResponseInvalid => new("ACQUIRE_RESPONSE_INVALID",
            "The HTTP response is not a supported identity-encoded artifact response.",
            "Use the exact HTTPS source with a bounded 200 response for a new transfer or exact 206 range response for resume."),
        ArtifactAcquisitionFailure.RangeUnsupported => new("ACQUIRE_RANGE_UNSUPPORTED",
            "The source did not establish byte-range support required for safe resume.",
            "Resume requires an exact 206 response and matching logical content identity; GitHub file validators remain required. A full response is never silently appended or restarted."),
        ArtifactAcquisitionFailure.ResumeStateMismatch => new("ACQUIRE_RESUME_MISMATCH",
            "The owned partial length, durable progress, or returned content range disagrees.",
            "Preserve the exact journal and partial for review or explicitly discard only this owned transaction before starting again."),
        ArtifactAcquisitionFailure.SourceChanged => new("ACQUIRE_SOURCE_CHANGED",
            "The source ETag or Last-Modified identity changed during resume.",
            "The owned partial was discarded when safe. Re-inspect H02 source identity and approve a completely new acquisition; no automatic restart occurred."),
        ArtifactAcquisitionFailure.ContentLengthMismatch => new("ACQUIRE_LENGTH_MISMATCH",
            "The response length or completed byte count differs from the exact manifest size.",
            "Treat the response as corrupt, review the source, and approve a new acquisition only after the discrepancy is resolved."),
        ArtifactAcquisitionFailure.SizeExceeded => new("ACQUIRE_SIZE_EXCEEDED",
            "The response attempted to exceed the exact manifest byte count.",
            "Treat the source as invalid. No excess byte is finalized, decompressed, or executed."),
        ArtifactAcquisitionFailure.IntegrityMismatch => new("ACQUIRE_HASH_MISMATCH",
            "Read-back SHA-256 does not match the exact manifest content pin.",
            "Treat the bytes as corrupt. File acquisition may discard its owned partial; image acquisition requires a fresh reviewed quarantine/reacquisition action."),
        ArtifactAcquisitionFailure.PartialConflict => new("ACQUIRE_PARTIAL_CONFLICT",
            "A partial file exists without exact matching H05b ownership evidence.",
            "Preserve the file and journal for review. Do not overwrite, append, truncate, or delete an unowned partial."),
        ArtifactAcquisitionFailure.FinalConflict => new("ACQUIRE_FINAL_CONFLICT",
            "The final destination exists without exact matching verified H05b evidence.",
            "Preserve the file. Reconcile its ownership and hash explicitly; H05b will not overwrite or execute it."),
        ArtifactAcquisitionFailure.JournalCorrupt => new("ACQUIRE_JOURNAL_CORRUPT",
            "The acquisition journal is malformed, inconsistent, or fails its integrity seal.",
            "Preserve the journal and exact pending sibling. Do not infer progress, truncate it, or overwrite associated files."),
        ArtifactAcquisitionFailure.JournalTooLarge => new("ACQUIRE_JOURNAL_TOO_LARGE",
            "The acquisition journal exceeds its purpose-specific size bound.",
            "Preserve it and investigate unexpected growth: file journals allow 128 KiB and image journals 512 KiB. Neither is truncated or replaced."),
        ArtifactAcquisitionFailure.JournalChanged => new("ACQUIRE_JOURNAL_CHANGED",
            "The acquisition journal changed after preview or has an owned pending write.",
            "Stop the concurrent transaction, preserve both exact files, and preview the authoritative state again."),
        ArtifactAcquisitionFailure.JournalIoFailure => new("ACQUIRE_JOURNAL_IO",
            "The acquisition journal could not be durably read or replaced.",
            "Check only the owned artifact directory, disk, and permissions. Do not elevate or delete unrelated files."),
        ArtifactAcquisitionFailure.DiskFull => new("ACQUIRE_DISK_FULL",
            "The destination filesystem reported no remaining space.",
            "Preserve the exact owned partial and journal, free reviewed space, and preview again. A mismatched checkpoint requires explicit owned cleanup."),
        ArtifactAcquisitionFailure.AccessDenied => new("ACQUIRE_ACCESS_DENIED",
            "The exact owned artifact path could not be accessed.",
            "Check the configured artifact-directory ownership and policy. Do not run as root merely to hide the failure."),
        ArtifactAcquisitionFailure.StorageFailed => new("ACQUIRE_STORAGE_FAILED",
            "The bounded partial write, read-back, flush, or atomic finalize failed.",
            "Preserve the exact owned files, inspect the destination filesystem, and reconcile before a new attempt."),
        ArtifactAcquisitionFailure.Timeout => new("ACQUIRE_TIMEOUT",
            "The single approved transfer exceeded its bounded request window.",
            "Create a fresh preview to resume only if the exact validator, range, partial, and journal state still agree. There is no automatic retry."),
        ArtifactAcquisitionFailure.Canceled => new("ACQUIRE_CANCELED",
            "The transfer was canceled before finalization.",
            "Create a fresh preview to resume only the exact owned partial with matching source validators and range state."),
        ArtifactAcquisitionFailure.ProgressFailed => new("ACQUIRE_PROGRESS_FAILED",
            "The injected progress observer failed.",
            "Repair the local observer and preview current durable bytes before another attempt; transfer success is never inferred from missing progress."),
        ArtifactAcquisitionFailure.RegistryAuthenticationRejected => new("ACQUIRE_REGISTRY_AUTH_REJECTED",
            "The registry did not provide the exact supported anonymous pull authorization.",
            "Review the named registry policy and public availability. Private credentials, broader scopes and alternate token endpoints are unsupported."),
        ArtifactAcquisitionFailure.ImageMetadataInvalid => new("ACQUIRE_IMAGE_METADATA_INVALID",
            "The image response is not supported bounded image metadata.",
            "Review the pinned index, manifest and config. Foreign URLs, plugins, artifact payloads and unsupported media types are not acquired."),
        ArtifactAcquisitionFailure.ImageInventoryMismatch => new("ACQUIRE_IMAGE_INVENTORY_MISMATCH",
            "Verified image descriptors disagree with the selected catalog closure.",
            "Review the exact catalog digests, byte counts and ordered layer occurrences before approving another acquisition."),
        ArtifactAcquisitionFailure.ImagePlatformMismatch => new("ACQUIRE_IMAGE_PLATFORM_MISMATCH",
            "The verified image platform is missing, ambiguous or different from the selected platform.",
            "Select and review an exact supported linux/amd64 manifest; no other platform is silently substituted."),
        ArtifactAcquisitionFailure.ImageBudgetExceeded => new("ACQUIRE_IMAGE_BUDGET_EXCEEDED",
            "The image transaction exhausted its approved transfer or request allowance.",
            "Review a new bounded acquisition plan. No automatic retries or increased byte allowance are permitted."),
        ArtifactAcquisitionFailure.ImageRecoveryRequired => new("ACQUIRE_IMAGE_RECOVERY_REQUIRED",
            "The owned image batch requires explicit quarantine and reacquisition.",
            "Review exact ownership, retained bytes and the full replacement budget. Foreign files and an occupied quarantine slot must be preserved."),
        ArtifactAcquisitionFailure.ImagePublicationUncertain => new("ACQUIRE_IMAGE_PUBLICATION_UNCERTAIN",
            "Complete image layout publication could not be confirmed.",
            "Preserve the journal and both exact directory paths. A fresh review must verify all root and content identities before completing publication."),
        ArtifactAcquisitionFailure.ImageLeaseUnavailable => new("ACQUIRE_IMAGE_LEASE_UNAVAILABLE",
            "An exclusive owned image acquisition lease could not be established.",
            "Wait for the active writer or review the exact preserved lease and journal. Unsupported locking and unknown ownership cannot be bypassed."),
        _ => throw new ArgumentOutOfRangeException(nameof(failure))
    };
}

public sealed class ArtifactAcquisitionException : Exception
{
    public ArtifactAcquisitionFailure Failure { get; }
    public ArtifactAcquisitionRemedy Remedy => ArtifactAcquisitionRemedies.For(Failure);

    internal ArtifactAcquisitionException(ArtifactAcquisitionFailure failure, Exception? inner = null)
        : base(ArtifactAcquisitionRemedies.For(failure).Summary)
    {
        _ = inner;
        Failure = failure;
    }
}
