<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Martlet.Gateway\Martlet.Gateway.csproj" />
    <InternalsVisibleTo Include="Martlet.Gateway.Persistence.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Persistence.Portable.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Persistence.Linux.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux.Native.Tests" />
  </ItemGroup>
</Project>
