<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Martlet.Gateway.Persistence\Martlet.Gateway.Persistence.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Audio2Face\Martlet.Gateway.Audio2Face.csproj" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux.Native.Tests" />
  </ItemGroup>
</Project>
