<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Martlet.Gateway.Persistence\Martlet.Gateway.Persistence.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Audio2Face\Martlet.Gateway.Audio2Face.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Ollama\Martlet.Gateway.Ollama.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.F5\Martlet.Gateway.F5.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Xtts\Martlet.Gateway.Xtts.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.GptSovits\Martlet.Gateway.GptSovits.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Dia\Martlet.Gateway.Dia.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Stt\Martlet.Gateway.Stt.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Singing\Martlet.Gateway.Singing.csproj" />
    <ProjectReference Include="..\Martlet.Gateway.Pictures\Martlet.Gateway.Pictures.csproj" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux.Tests" />
    <InternalsVisibleTo Include="Martlet.Gateway.Host.Linux.Native.Tests" />
  </ItemGroup>
</Project>
